#version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=automl_mlops,mlflow,airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.3.1
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://user:password@db/mlflow
    command: >
      bash -c "pip install psycopg2-binary &&
               mlflow server --host 0.0.0.0 --port 5000 
               --backend-store-uri postgresql://user:password@db/mlflow 
               --default-artifact-root /mlflow"
    volumes:
      - ./mlflow:/mlflow
    depends_on:
      - db

  airflow:
    image: apache/airflow:2.2.3
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://user:password@db/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/automl_mlops
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - db
      - mlflow
      - airflow

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: